// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx6x_j4u3XUFnJfON0Z7Do2fOZEuvCJr8',
    appId: '1:553615960147:web:60c6ab818cdb6b7800bea6',
    messagingSenderId: '553615960147',
    projectId: 'fir-test-22b38',
    authDomain: 'fir-test-22b38.firebaseapp.com',
    storageBucket: 'fir-test-22b38.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEr7f6riPnK4Ck61CkC5pExYzFzqKzTmY',
    appId: '1:553615960147:android:d3c055c31e693fa300bea6',
    messagingSenderId: '553615960147',
    projectId: 'fir-test-22b38',
    storageBucket: 'fir-test-22b38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT4YrjiqyNVe1d_csg2gY75HY6El7OdcU',
    appId: '1:553615960147:ios:61b543bd1e1c806100bea6',
    messagingSenderId: '553615960147',
    projectId: 'fir-test-22b38',
    storageBucket: 'fir-test-22b38.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT4YrjiqyNVe1d_csg2gY75HY6El7OdcU',
    appId: '1:553615960147:ios:61b543bd1e1c806100bea6',
    messagingSenderId: '553615960147',
    projectId: 'fir-test-22b38',
    storageBucket: 'fir-test-22b38.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx6x_j4u3XUFnJfON0Z7Do2fOZEuvCJr8',
    appId: '1:553615960147:web:a936e48f8d72a46d00bea6',
    messagingSenderId: '553615960147',
    projectId: 'fir-test-22b38',
    authDomain: 'fir-test-22b38.firebaseapp.com',
    storageBucket: 'fir-test-22b38.firebasestorage.app',
  );
}
